// <auto-generated />
namespace SklepWPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MessageModificationAndAdminFieldInUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MessageModificationAndAdminFieldInUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201906061223268_MessageModificationAndAdminFieldInUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
